In [2]:
%matplotlib inline

In [3]:
import cv2
import numpy as np
from matplotlib import pyplot as plt
from scipy.ndimage import convolve

In [4]:
def cropFace(image):
    faceClassifier = cv2.CascadeClassifier('/home/jad/machineLearningVenv/lib/python3.5/site-packages/cv2/data/haarcascade_frontalface_alt.xml')
    faces = faceClassifier.detectMultiScale(image)
    #get first face coordinates
    xFace, yFace, wFace, hFace = faces[0]
    croppedFace = image[yFace:yFace+hFace, xFace:xFace+wFace]
    return croppedFace

In [5]:
img = cv2.imread('/home/jad/Téléchargements/sur.png', 0)
img = cropFace(img)
S = np.matrix([[ 5,  5,  5],
               [-3,  0, -3],
               [-3, -3, -3]
              ])
SE = np.matrix([[ 5,  5, -3],
                [ 5,  0, -3],
                [-3, -3, -3]
               ])
E = np.matrix([[5, -3, -3],
               [5,  0, -3],
               [5, -3, -3]
              ])
NE = np.matrix([[-3, -3, -3],
                [ 5,  0, -3],
                [ 5,  5, -3]
               ])
N = np.matrix([[-3, -3, -3],
               [-3,  0, -3],
               [ 5,  5,  5]
              ])
NW = np.matrix([[-3, -3, -3],
                [-3,  0,  5],
                [-3,  5,  5]
               ])
W = np.matrix([[-3, -3, 5],
               [-3,  0, 5],
               [-3, -3, 5]
              ])
SW = np.matrix([[-3,  5,  5],
                [-3,  0,  5],
                [-3, -3, -3]
               ])

res1 = convolve(img, N)
res2 = convolve(img, NE)
res3 = convolve(img, E)
res4 = convolve(img, SE)
res5 = convolve(img, S)
res6 = convolve(img, SW)
res7 = convolve(img, W)
res8 = convolve(img, NW)

# plt.imshow(res1, cmap='gray')
# plt.show()
# plt.imshow(res2, cmap='gray')
# plt.show()
# plt.imshow(res3, cmap='gray')
# plt.show()
# plt.imshow(res4, cmap='gray')
# plt.show()
# plt.imshow(res5, cmap='gray')
# plt.show()
# plt.imshow(res6, cmap='gray')
# plt.show()
# plt.imshow(res7, cmap='gray')
# plt.show()
# plt.imshow(res8, cmap='gray')


In [6]:
print(img)
def hvnLBP(image):
    height, width = image.shape
    for i in range(width):
        for j in range(height):
            row1=img[i-1][j-1]
            print("img[%d,%d] ="%(i,j), img[i][j], row1)
            
hvnLBP(img)

[[ 75  59  60 ... 172 170 162]
 [ 52  46  51 ... 167 172 168]
 [ 51  51  54 ... 162 174 176]
 ...
 [ 55  52  49 ...  62  49  54]
 [ 54  50  52 ...  55  52  48]
 [ 65  48  52 ...  51  56  54]]
img[0,0] = 75 54
img[0,1] = 59 65
img[0,2] = 60 48
img[0,3] = 60 52
img[0,4] = 57 63
img[0,5] = 52 60
img[0,6] = 46 59
img[0,7] = 46 55
img[0,8] = 52 62
img[0,9] = 61 58
img[0,10] = 57 61
img[0,11] = 52 57
img[0,12] = 56 50
img[0,13] = 64 38
img[0,14] = 63 35
img[0,15] = 80 22
img[0,16] = 105 28
img[0,17] = 94 31
img[0,18] = 89 46
img[0,19] = 88 54
img[0,20] = 98 61
img[0,21] = 92 77
img[0,22] = 93 104
img[0,23] = 93 110
img[0,24] = 85 127
img[0,25] = 75 132
img[0,26] = 64 136
img[0,27] = 73 142
img[0,28] = 74 142
img[0,29] = 74 145
img[0,30] = 79 149
img[0,31] = 81 150
img[0,32] = 81 151
img[0,33] = 95 147
img[0,34] = 105 141
img[0,35] = 105 139
img[0,36] = 104 141
img[0,37] = 109 135
img[0,38] = 107 136
img[0,39] = 109 146
img[0,40] = 104 148
img[0,41] = 103 155
img[0,42] = 117 157
img[0,43] = 1