In [2]:
%matplotlib inline

In [3]:
import cv2
import numpy as np
from matplotlib import pyplot as plt
from scipy.ndimage import convolve

In [11]:
def cropFace(image):
    faceClassifier = cv2.CascadeClassifier('./haarcascade/haarcascade_frontalface_alt.xml')
    faces = faceClassifier.detectMultiScale(image)
    #get first face coordinates
    xFace, yFace, wFace, hFace = faces[0]
    croppedFace = image[yFace:yFace+hFace, xFace:xFace+wFace]
    return croppedFace

In [12]:
img = cv2.imread('sur.png', 0)
img = cropFace(img)
S = np.matrix([[ 5,  5,  5],
               [-3,  0, -3],
               [-3, -3, -3]
              ])
SE = np.matrix([[ 5,  5, -3],
                [ 5,  0, -3],
                [-3, -3, -3]
               ])
E = np.matrix([[5, -3, -3],
               [5,  0, -3],
               [5, -3, -3]
              ])
NE = np.matrix([[-3, -3, -3],
                [ 5,  0, -3],
                [ 5,  5, -3]
               ])
N = np.matrix([[-3, -3, -3],
               [-3,  0, -3],
               [ 5,  5,  5]
              ])
NW = np.matrix([[-3, -3, -3],
                [-3,  0,  5],
                [-3,  5,  5]
               ])
W = np.matrix([[-3, -3, 5],
               [-3,  0, 5],
               [-3, -3, 5]
              ])
SW = np.matrix([[-3,  5,  5],
                [-3,  0,  5],
                [-3, -3, -3]
               ])

res1 = convolve(img, N)
res2 = convolve(img, NE)
res3 = convolve(img, E)
res4 = convolve(img, SE)
res5 = convolve(img, S)
res6 = convolve(img, SW)
res7 = convolve(img, W)
res8 = convolve(img, NW)

# plt.imshow(res1, cmap='gray')
# plt.show()
# plt.imshow(res2, cmap='gray')
# plt.show()
# plt.imshow(res3, cmap='gray')
# plt.show()
# plt.imshow(res4, cmap='gray')
# plt.show()
# plt.imshow(res5, cmap='gray')
# plt.show()
# plt.imshow(res6, cmap='gray')
# plt.show()
# plt.imshow(res7, cmap='gray')
# plt.show()
# plt.imshow(res8, cmap='gray')


array([ 62,  56,  48,  44,  52,  59,  56,  46,  39,  34,  50,  53,  74,
        86,  78,  78,  79,  71,  67,  65,  66,  61,  70,  66,  65,  71,
        75,  82,  89,  93,  95, 101, 104, 114, 115,  90,  76,  87, 100,
       105, 108, 115, 117, 116,  96, 100, 112, 128, 126, 120, 125, 134,
       105, 114, 122, 133, 155, 163, 167, 167, 170, 169, 169, 173, 171,
       168, 158, 158, 157, 133, 139, 141, 126, 129, 149, 164, 168, 174,
       165, 164, 163, 139, 132, 135, 142, 144, 139, 129, 137, 149, 146,
       148, 146, 117,  91,  92, 104, 119, 143, 144, 141, 136, 133, 114,
        92,  92,  85,  74,  67,  73,  67,  66,  59,  66,  73,  85,  75,
       121,  86,  78,  69,  76,  63,  59,  64,  65,  70,  74,  77,  72,
        80,  82,  73,  81,  72,  74,  69,  65,  59,  63,  60,  78,  66,
        80,  82,  76,  89,  98, 101, 114, 151, 176, 166, 179], dtype=uint8)

In [83]:
# print(img)
def hvnLBP(image):
    def hLBP(matrix):
        mat = matrix.copy()
        print(mat)
        for i in range(mat.shape[1]):
            maxNum = np.amax(mat[i, :])
            for j in range(mat.shape[0]):
                print(mat[i, j])
                mat[i, j] = 1 if mat[i, j] == maxNum and maxNum != 0 else 0
        return mat
            
        
    def vLBP(matrix):
        pass
    height, width = image.shape
    for i in range(height):
        for j in range(width):
            if i == 0: # top border
                if j == 0: # top left corner
                    row1 = np.array([0, 0, 0])
                    row2 = np.array([0, -1, img[i][j+1]])
                    row3 = np.hstack((np.array([0]), img[i+1][j:j+2]))
                    mat = np.matrix([row1, row2, row3])
                    hLBP(mat)
                    break
                elif j == width -1: # top right corner
                    pass
                else:
                    pass
            elif i == height -1: # bottom border
                if j == 0: # bottom left corner
                    pass
                elif j == width -1: # bottom right corner
                    pass
                else:
                    pass
            else:
                if j == 0: # left border
                    pass
                elif j == width -1: # right border
                    pass
                else:
                    pass
            
            row1=img[i-1][j-1:j+2]
            row2=img[i][j-1:j+2]
            row3=img[i+1][j-1:j+2]
            print(row1)
            print(row2)
            print(row3)
            matrix = np.matrix([row1, row2, row3])
            print("img[%d,%d] ="%(i, j), img[i][j], matrix)
        break
            
hvnLBP(img)

[[ 0  0  0]
 [ 0 -1 59]
 [ 0 52 46]]
0
0
0
0
-1
59
0
52
46
[[0 0 0]
 [0 0 1]
 [0 1 0]]
